name: CD

on:
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci --silent
      - name: Build Android Release
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease
      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/app/build/outputs/apk/release/app-release.apk
          asset_name: interconnected-${{ github.ref_name }}.apk
          tag: ${{ github.ref }}
